# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 373)
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(Dialog)
        self.tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setObjectName("tabs")
        self.driver_tab = QtWidgets.QWidget()
        self.driver_tab.setObjectName("driver_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.driver_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.driver_tab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.driver_path = QtWidgets.QLineEdit(self.driver_tab)
        self.driver_path.setObjectName("driver_path")
        self.horizontalLayout_2.addWidget(self.driver_path)
        self.tabs.addTab(self.driver_tab, "")
        self.files_tab = QtWidgets.QWidget()
        self.files_tab.setObjectName("files_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.files_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.files_tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.image_output_path = QtWidgets.QLineEdit(self.files_tab)
        self.image_output_path.setObjectName("image_output_path")
        self.horizontalLayout_4.addWidget(self.image_output_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.files_tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.csv_output = QtWidgets.QLineEdit(self.files_tab)
        self.csv_output.setObjectName("csv_output")
        self.horizontalLayout_7.addWidget(self.csv_output)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.files_tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.text_output_path = QtWidgets.QLineEdit(self.files_tab)
        self.text_output_path.setObjectName("text_output_path")
        self.horizontalLayout_3.addWidget(self.text_output_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.files_tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.links_path = QtWidgets.QLineEdit(self.files_tab)
        self.links_path.setObjectName("links_path")
        self.horizontalLayout_8.addWidget(self.links_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.tabs.addTab(self.files_tab, "")
        self.services_tab = QtWidgets.QWidget()
        self.services_tab.setObjectName("services_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.services_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.paragraph_checkbox = QtWidgets.QCheckBox(self.services_tab)
        self.paragraph_checkbox.setObjectName("paragraph_checkbox")
        self.horizontalLayout_6.addWidget(self.paragraph_checkbox)
        self.sentence_checkbox = QtWidgets.QCheckBox(self.services_tab)
        self.sentence_checkbox.setObjectName("sentence_checkbox")
        self.horizontalLayout_6.addWidget(self.sentence_checkbox)
        self.images_checkbox = QtWidgets.QCheckBox(self.services_tab)
        self.images_checkbox.setObjectName("images_checkbox")
        self.horizontalLayout_6.addWidget(self.images_checkbox)
        self.csv_checkbox = QtWidgets.QCheckBox(self.services_tab)
        self.csv_checkbox.setObjectName("csv_checkbox")
        self.horizontalLayout_6.addWidget(self.csv_checkbox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.load_links_checkbox = QtWidgets.QCheckBox(self.services_tab)
        self.load_links_checkbox.setObjectName("load_links_checkbox")
        self.horizontalLayout_5.addWidget(self.load_links_checkbox)
        self.save_result_checkbox = QtWidgets.QCheckBox(self.services_tab)
        self.save_result_checkbox.setObjectName("save_result_checkbox")
        self.horizontalLayout_5.addWidget(self.save_result_checkbox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tabs.addTab(self.services_tab, "")
        self.verticalLayout.addWidget(self.tabs)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_button = QtWidgets.QPushButton(Dialog)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.close_button = QtWidgets.QPushButton(Dialog)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Driver path"))
        self.tabs.setTabText(self.tabs.indexOf(self.driver_tab), _translate("Dialog", "Driver"))
        self.label_2.setText(_translate("Dialog", "Images output"))
        self.label_8.setText(_translate("Dialog", "CSV output"))
        self.label_3.setText(_translate("Dialog", "Text output"))
        self.label_4.setText(_translate("Dialog", "Links input"))
        self.tabs.setTabText(self.tabs.indexOf(self.files_tab), _translate("Dialog", "Files"))
        self.paragraph_checkbox.setText(_translate("Dialog", "Paragraphs"))
        self.sentence_checkbox.setText(_translate("Dialog", "Sentences"))
        self.images_checkbox.setText(_translate("Dialog", "Images"))
        self.csv_checkbox.setText(_translate("Dialog", "CSV"))
        self.load_links_checkbox.setText(_translate("Dialog", "Load links from file"))
        self.save_result_checkbox.setText(_translate("Dialog", "Save text result to file"))
        self.tabs.setTabText(self.tabs.indexOf(self.services_tab), _translate("Dialog", "Services"))
        self.save_button.setText(_translate("Dialog", "Save"))
        self.close_button.setText(_translate("Dialog", "Close"))

